require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'BluecherryMobile' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-vlc-media-player', :path => '../node_modules/react-native-vlc-media-player'

  pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker'

  pod 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec'

  target 'BluecherryMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'BluecherryMobile-tvOS' do
  # Pods for BluecherryMobile-tvOS

  target 'BluecherryMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
